Fix missing import of jenkins.model.*
Without this import I get an error saying:

groovy.lang.MissingPropertyException: No such property: Jenkins for class ...